name: Fix formatting

on: [push]
permissions:
  contents: write

jobs:
  fix-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Generate MobiVM MetalANGLE backend
        run: |
          ./gradlew :backends:gdx-backend-robovm-metalangle:generate 
          ./gradlew :backends:gdx-backend-robovm-metalangle:spotlessApply
      - name: Commit generation changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add backends/gdx-backend-robovm-metalangle/src
          git commit -m "Generate MobiVM MetalANGLE backend" -a
        continue-on-error: true
      - name: Apply formatter
        run: ./gradlew spotlessApply
      - name: Commit formatting changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Apply formatter" -a
        continue-on-error: true
      - name: Push formatting changes
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
